// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8CJtbmr7Ezt1l13PtPbj5S_pl3tjNDIY',
    appId: '1:602783046019:web:752cdc2b993126c9ae3eb6',
    messagingSenderId: '602783046019',
    projectId: 'gamewise-6d228',
    authDomain: 'gamewise-6d228.firebaseapp.com',
    storageBucket: 'gamewise-6d228.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEjcrF1ZoMYgsGw2ObJA84Orht5ETGpe0',
    appId: '1:602783046019:android:a643747cf18db284ae3eb6',
    messagingSenderId: '602783046019',
    projectId: 'gamewise-6d228',
    storageBucket: 'gamewise-6d228.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC73TOxhRwHjlwZEL-SL9H79DaEUpbwh4A',
    appId: '1:602783046019:ios:416b50979dad9fa5ae3eb6',
    messagingSenderId: '602783046019',
    projectId: 'gamewise-6d228',
    storageBucket: 'gamewise-6d228.firebasestorage.app',
    iosClientId: '602783046019-vkdgoem30bgnqvgkc5c3pjtvm53kadru.apps.googleusercontent.com',
    iosBundleId: 'com.example.gamewiseWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC73TOxhRwHjlwZEL-SL9H79DaEUpbwh4A',
    appId: '1:602783046019:ios:416b50979dad9fa5ae3eb6',
    messagingSenderId: '602783046019',
    projectId: 'gamewise-6d228',
    storageBucket: 'gamewise-6d228.firebasestorage.app',
    iosClientId: '602783046019-vkdgoem30bgnqvgkc5c3pjtvm53kadru.apps.googleusercontent.com',
    iosBundleId: 'com.example.gamewiseWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8CJtbmr7Ezt1l13PtPbj5S_pl3tjNDIY',
    appId: '1:602783046019:web:bc1dd29aae974abdae3eb6',
    messagingSenderId: '602783046019',
    projectId: 'gamewise-6d228',
    authDomain: 'gamewise-6d228.firebaseapp.com',
    storageBucket: 'gamewise-6d228.firebasestorage.app',
  );

}